### ISSUE TITLE
Animation doesn't support % properties

### ISSUE THREAD

**Issue by thk123** [kaisellgren/Animation#14]
The regex in the [element_animation.dart](https://github.com/kaisellgren/Animation/blob/master/lib/src/element_animation.dart) rules them out:

```
var match = new RegExp(r'^(-?[0-9\.]+)([a-zA-Z]+)$').firstMatch(cssValue);
```

On both line 73 and 108 in element_animation.dart

Would at least need adjust the regex to match the percentage sign.

```
var match = new RegExp(r'^(-?[0-9\.]+)([a-zA-Z%]+)$').firstMatch(cssValue
```

I have fixed this. The problem is then, when we get the property from the element, it always ends up receiving it in pixels, despite being set as a percentage in my style sheet. 

This then reveals another issue, 

```
style.getPropertyValue("top") // returns ###px even when not set as a pixel measurement
```

 for property say `top` always returns the value in px despite the property being set as a percentage.

This method is in html-dartium, so I don't know if it is a bug in there instead of here. 

In any case, we should probably error if the units don't match as it doesn't make sense to interpolate between 50px and 1.2em in any case.

**Comment by kaisellgren** [comment]
Ok it's now working, thanks for the report and sorry it took a while.
