### ISSUE TITLE
animate calls StyleAnimation.setProperties method causing Object._noSuchMethod error

### ISSUE THREAD

**Issue by imiten** [kaisellgren/Animation#4]
Hi,

I have html doc with header element as Bookmarks.  You can see in output I print it.  I then want to animate the jquery code commented in myanimate method below using Animation package but it gives exception as below. 

void myanimate([Timer t]) {
  var header = query('body header');
  print(header.text);
  /*
-  $element.animate({opacity:0.2}).delay(1000)
                  .animate({opacity:0.4}).delay(1000)
                  .animate({opacity:0.6}).delay(1000)
                  .animate({opacity:0.8}).delay(1000)
                  .animate({opacity:1}).delay(1000)
                  .animate({opacity:0.8}).delay(1000)
                  .animate({opacity:0.6}).delay(1000)
                  .animate({opacity:0.4}).delay(1000)
                  .animate({opacity:0.2}).delay(1000);
                  */
  var opacity = [0.2, 0.4, 0.6, 0.8, 1, 0.8, 0.6, 0.4, 0.2];
  
  opacity.forEach((opa) => animate(element:header, 
      duration:1000, properties : {"opacity": opa}
  ));

}

```
Bookmarks
Exception: NullPointerException : method: 'group'
Receiver: null
Arguments: [1]
Stack Trace: #0      Object._noSuchMethod (dart:core-patch:1261:3)
#1      Object.noSuchMethod (dart:core-patch:1264:25)
#2      StyleAnimation.setProperties.<anonymous closure>.<anonymous closure> (http://127.0.0.1:3030/E:/learn/dart/bookmarks/src/style_animation.dart:46:34)
#3      _LinkedHashMapImpl.forEach._ (bootstrap:1295:8)
#4      DoubleLinkedQueue.forEach (bootstrap:1554:8)
#5      _LinkedHashMapImpl.forEach (bootstrap:1294:18)
#6      StyleAnimation.setProperties.<anonymous closure> (http://127.0.0.1:3030/E:/learn/dart/bookmarks/src/style_animation.dart:38:27)
#7      _FutureImpl._complete (bootstrap:840:19)
#8      _FutureImpl._complete (bootstrap:848:5)
#9      _FutureImpl._setValue (bootstrap:862:14)
#10     _CompleterImpl.complete (bootstrap:945:26)
#11     _completeMeasurementFutures._completeMeasurementFutures (E:\b\build\slave\dartium-win-full-trunk\build\src\dart\sdk\lib\html\src\Measurement.dart:115:35)
#12     _MeasurementScheduler._onCallback (E:\b\build\slave\dartium-win-full-trunk\build\src\dart\sdk\lib\html\src\Measurement.dart:34:19)
#13     _MutationObserverScheduler._handleMutation._handleMutation (E:\b\build\slave\dartium-win-full-trunk\build\src\dart\sdk\lib\html\src\Measurement.dart:63:21)
```

Refused to set unsafe header "User-Agent"

Regards,

Miten

**Comment by kaisellgren** [comment]
Hi,

This is related to this issue https://github.com/kaisellgren/Animation/issues/2

In essence, only width/height/top/left and such are currently supported. I am going to support a wide array of CSS properties -- but I've been sick past 8 days straight (more or less) so I've been unable to get this done.

So simply put, the current version does not work with 'opacity', sadly. I want to fix this, but I'm now quite sick and I hope I can get it fixed soon.

**Comment by kaisellgren** [comment]
This should work now, but there are still some properties that can't be animated (colors and text-shadow). Now you should be able to animate plenty of stuff though.

**Comment by imiten** [comment]
Hi,

could you take look at issue#7 which you closed has my use case.
https://github.com/kaisellgren/Animation/issues/7

I am trying to replace my existing jquery animation with dart animation using your lib.

Also may be explain why code I have is not animating as needed.

Regards,

Miten.
